# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value
    evento: 'Feria Matemática 2019'
    actividad1: Matemáticas y Braille
    actividad1m: 3
    actividad1v: 3
    actividad2: Burbujas
    actividad2m: 6
    actividad2v: 6
    actividad3: Canguro Matemático
    actividad3m: 5
    actividad3v: 5
    actividad4: Club de Mate
    actividad4m: 6
    actividad4v: 6
    actividad5: Laberintos y Superficies
    actividad5m: 4
    actividad5v: 4
    actividad6: Túneles bajo el suelo - IIES
    actividad6m: 4
    actividad6v: 4
    actividad7: Expo Mates (Algoritmos)
    actividad7m: 4
    actividad7v: 4
    actividad8: Papiroflexia
    actividad8m: 4
    actividad8v: 4
    actividad9: Geometría euclidiana y Geografía - CIGA
    actividad9m: 4
    actividad9v: 4
    actividad10: ARTEMAT - IM Cuernavaca
    actividad10m: 4
    actividad10v: 4
    actividad11: Museo Matemático
    actividad11m: 2
    actividad11v: 2
    actividad12: Mosaicos en Desorden (Penrose)
    actividad12m: 6
    actividad12v: 6
    actividad13: Máquina de Galton y Astronomía / Planetario - IRyA
    actividad13m: 8
    actividad13v: 8
    actividad14: Matemagia
    actividad14m: 2
    actividad14v: 2
    actividad15: Nudos y Pantalones locos
    actividad15m: 8
    actividad15v: 8
    actividad16: El fotón en su laberinto - IGUM
    actividad16m: 4
    actividad16v: 4

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
