<?php

namespace RegistroBundle\Repository;
use RegistroBundle\Entity\Registro;
use Symfony\Component\PropertyAccess\PropertyAccess;


use Doctrine\ORM\EntityRepository;


/**
 * RegistroRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */

class RegistroRepository extends EntityRepository
{
    public function countActividad($horario)
    {
        $accessor = PropertyAccess::createPropertyAccessor();
        $registros = $this->findByActivo(true);
        $actividad2 = $actividad1 = $actividad3 = $actividad4 = $actividad5 = $actividad6 =
        $actividad7 = $actividad8 = $actividad9 = $actividad10 = $actividad12 = $actividad11 = $actividad13 =
        $actividad14 = $actividad15 = $actividad16 = 0;

        foreach ($registros as $registro) {
            $actividad = array_search(true, $accessor->getValue($registro, $horario));
            switch ($actividad) {
                case 'actividad1':
                    $actividad1 = $actividad1 + 1;
                    break;
                case 'actividad2':
                    $actividad2 = $actividad2 + 1;
                    break;
                case 'actividad3':
                    $actividad3 = $actividad3 + 1;
                    break;
                case 'actividad4':
                    $actividad4 = $actividad4 + 1;
                    break;
                case 'actividad5':
                    $actividad5 = $actividad5 + 1;
                    break;
                case 'actividad6':
                    $actividad6 = $actividad6 + 1;
                    break;
                case 'actividad7':
                    $actividad7 = $actividad7 + 1;
                    break;
                case 'actividad8':
                    $actividad8 = $actividad8 + 1;
                    break;
                case 'actividad9':
                    $actividad9 = $actividad9 + 1;
                    break;
                case 'actividad10':
                    $actividad10 = $actividad10 + 1;
                    break;
                case 'actividad11':
                    $actividad11 = $actividad11 + 1;
                    break;
                case 'actividad12':
                    $actividad12 = $actividad12 + 1;
                    break;
                case 'actividad13':
                    $actividad13 = $actividad13 + 1;
                    break;
                case 'actividad14':
                    $actividad14 = $actividad14 + 1;
                    break;
                case 'actividad15':
                    $actividad15 = $actividad15 + 1;
                    break;
                case 'actividad16':
                    $actividad16 = $actividad16 + 1;
                    break;

            }
        }

        $total = array (
            'actividad1'=> $actividad1,
            'actividad2'=>$actividad2,
            'actividad3'=>$actividad3,
            'actividad4'=>$actividad4,
            'actividad5'=>$actividad5,
            'actividad6'=>$actividad6,
            'actividad7'=>$actividad7,
            'actividad8'=>$actividad8,
            'actividad9'=>$actividad9,
            'actividad10'=>$actividad10,
            'actividad11'=>$actividad11,
            'actividad12'=>$actividad12,
            'actividad13'=>$actividad13,
            'actividad14'=>$actividad14,
            'actividad15'=>$actividad15,
            'actividad16'=>$actividad16,
            );

        return $total;

    }

}